
function correlator_core_config(this_block)

  % Revision History:
  %
  %   18-Dec-2010  (17:25 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     C:\git\phringes\mssge\correlator_core.vhd
  %
  %

  this_block.setTopLevelLanguage('VHDL');

  this_block.setEntityName('correlator_core');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  %this_block.tagAsCombinational;

  this_block.addSimulinkInport('sync_in');
  this_block.addSimulinkInport('i0');
  this_block.addSimulinkInport('i1');
  this_block.addSimulinkInport('i2');
  this_block.addSimulinkInport('i3');
  this_block.addSimulinkInport('q0');
  this_block.addSimulinkInport('q1');
  this_block.addSimulinkInport('q2');
  this_block.addSimulinkInport('q3');
  this_block.addSimulinkInport('integ_time');
  this_block.addSimulinkInport('qdelay');
  this_block.addSimulinkInport('thresh');

  this_block.addSimulinkOutport('addr');
  this_block.addSimulinkOutport('data_in');
  this_block.addSimulinkOutport('we');
  this_block.addSimulinkOutport('integs');

  addr_port = this_block.port('addr');
  addr_port.setType('UFix_5_0');
  data_in_port = this_block.port('data_in');
  data_in_port.setType('UFix_32_0');
  integs_port = this_block.port('integs');
  integs_port.setType('UFix_32_0');
  we_port = this_block.port('we');
  we_port.setType('Bool');
  we_port.useHDLVector(false);

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('i0').width ~= 8);
      this_block.setError('Input data type for port "i0" must have width=8.');
    end

    if (this_block.port('i1').width ~= 8);
      this_block.setError('Input data type for port "i1" must have width=8.');
    end

    if (this_block.port('i2').width ~= 8);
      this_block.setError('Input data type for port "i2" must have width=8.');
    end

    if (this_block.port('i3').width ~= 8);
      this_block.setError('Input data type for port "i3" must have width=8.');
    end

    if (this_block.port('integ_time').width ~= 32);
      this_block.setError('Input data type for port "integ_time" must have width=32.');
    end

    if (this_block.port('q0').width ~= 8);
      this_block.setError('Input data type for port "q0" must have width=8.');
    end

    if (this_block.port('q1').width ~= 8);
      this_block.setError('Input data type for port "q1" must have width=8.');
    end

    if (this_block.port('q2').width ~= 8);
      this_block.setError('Input data type for port "q2" must have width=8.');
    end

    if (this_block.port('q3').width ~= 8);
      this_block.setError('Input data type for port "q3" must have width=8.');
    end

    if (this_block.port('qdelay').width ~= 11);
      this_block.setError('Input data type for port "qdelay" must have width=11.');
    end

    if (this_block.port('sync_in').width ~= 1);
      this_block.setError('Input data type for port "sync_in" must have width=1.');
    end

    this_block.port('sync_in').useHDLVector(false);

    if (this_block.port('thresh').width ~= 7);
      this_block.setError('Input data type for port "thresh" must have width=7.');
    end

  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'clk_1','ce_1')
   end  % if(inputRatesKnown)
  % -----------------------------

    % (!) Set the inout port rate to be the same as the first input 
    %     rate. Change the following code if this is untrue.
    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('correlator_core.vhd');

return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 & uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

